export const APP_NAME = "Mine Pile Visualizer";
export const APP_DESCRIPTION =
  "Local-first visualizer for circuit topology, live object state, stockpile content, and profiler history generated by a mineral tracking simulation engine.";
export const APP_VERSION = "0.01.014";
export const DEFAULT_APP_DATA_ROOT = ".local/app-data/v1";
export const DEFAULT_FULL_RENDER_THRESHOLD = 150_000;
export const DEFAULT_FULL_RENDER_STRIDE = 2;

export const NAV_ITEMS = [
  { href: "/circuit", label: "Circuit" },
  { href: "/live", label: "Live State" },
  { href: "/stockpiles", label: "Stockpiles" },
  { href: "/profiler", label: "Profiler" },
] as const;
